import {StyleSheet} from 'react-native';
import {colors} from '../../../assets/colors';

export default StyleSheet.create({
  fontStyle: {
    fontSize: 15,
    fontWeight: 'normal',
    color: colors.text,
  },
  imageIconStyle: {
    width: 25,
    height: 25,
    marginHorizontal: 6,
    tintColor: colors.text,
  },
  radioContentStyle: {
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    paddingBottom: 6,
  },
  booleanContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  booleanContentStyle: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.grey,
    padding: 8,
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  imageContainerStyle: {
    width: '32%',
    height: 100,
    marginTop: 12,
    backgroundColor: colors.white,
    borderRadius: 6,
    borderColor: colors.grey,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageInputStyle: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
    borderRadius: 6,
  },
  iconDeleteStyle: {
    width: 10,
    height: 10,
    tintColor: colors.white,
  },
  imageDeleteStyle: {
    backgroundColor: colors.black,
    opacity: 0.8,
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
  },
  inputLabelStyle: {
    width: '100%',
    borderRadius: 6,
    borderColor: colors.grey,
    borderWidth: 1,
    padding: 0,
    margin: 0,
    paddingVertical: 10,
    paddingHorizontal: 8,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.white,
    shadowColor: colors.black,
    marginVertical: 10,
  },
  imageRowStyle: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
});
